debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    co.jpa.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 8084
  
spring:
  main:    allow-bean-definition-overriding: true  datasource:
    url: jdbc:mariadb://localhost:3309/restboard?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: roots
  data:    rest:      base-path: /api  
      detection-strategy: annotated
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:      ddl-auto: update
    properties:
      hibernate:        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100